// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("OutlookAddIn2013")]
[assembly: AssemblyProductAttribute("sync-addin-for-outlook-and-jira")]
[assembly: AssemblyDescriptionAttribute("Sync Addin for Outlook and JIRA")]
[assembly: AssemblyVersionAttribute("1.0")]
[assembly: AssemblyFileVersionAttribute("1.0")]
[assembly: AssemblyConfigurationAttribute("Release")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyTitle = "OutlookAddIn2013";
        internal const System.String AssemblyProduct = "sync-addin-for-outlook-and-jira";
        internal const System.String AssemblyDescription = "Sync Addin for Outlook and JIRA";
        internal const System.String AssemblyVersion = "1.0";
        internal const System.String AssemblyFileVersion = "1.0";
        internal const System.String AssemblyConfiguration = "Release";
    }
}
