// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("OutlookAddin.Func")>]
[<assembly: AssemblyProductAttribute("sync-addin-for-outlook-and-jira")>]
[<assembly: AssemblyDescriptionAttribute("Sync Addin for Outlook and JIRA")>]
[<assembly: AssemblyVersionAttribute("1.0")>]
[<assembly: AssemblyFileVersionAttribute("1.0")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "OutlookAddin.Func"
    let [<Literal>] AssemblyProduct = "sync-addin-for-outlook-and-jira"
    let [<Literal>] AssemblyDescription = "Sync Addin for Outlook and JIRA"
    let [<Literal>] AssemblyVersion = "1.0"
    let [<Literal>] AssemblyFileVersion = "1.0"
    let [<Literal>] AssemblyConfiguration = "Release"
